#!/usr/bin/env python3

import sys
import argparse
import json
import yaml

from pddls.pddl2json import parseAsJson


def main():
    ap = argparse.ArgumentParser(description='Convert PDDL to Json (or YAML).')
    ap.add_argument('input_pddl_file',
                    help='input PDDL')
    ap.add_argument('--yaml', action='store_true', default=False,
                    help='output YAML instead of JSON')
    args = ap.parse_args()
    doc = parseAsJson(args.input_pddl_file)
    if args.yaml:
        print(yaml.dump(dict(doc), default_flow_style=False, indent=4))
    else:
        print(json.dumps(doc, indent=True))


if __name__ == '__main__':
    main()
